apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: default
  labels:
    app: bms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000  # Replace with the port your app runs on
  selector:
    app: bms
